---
- name: installing prerequisite packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - bc
    - curl
    - bison
    - g++-multilib
    - git
    - gperf
    - libxml2-utils
    - flex
    - gnupg
    - gperf
    - libesd0-dev
    - libncurses5-dev
    - libsdl1.2-dev
    - libxml2
    - libxml2-utils
    - imagemagick
    - lzop
    - pngcrush
    - schedtool
    - squashfs-tools
    - xsltproc
    - zip
    - zlib1g-dev
    - maven
    - openjdk-8-jdk
    - bsdmainutils
  become: yes

- name: creating ~/bin
  file:
    path: /home/dev/bin
    state: directory
    owner: dev
    group: dev

- name: download repo
  get_url:
    url: https://storage.googleapis.com/git-repo-downloads/repo
    dest: /home/dev/bin/repo
    checksum: sha256:e147f0392686c40cfd7d5e6f332c6ee74c4eab4d24e2694b3b0a0c037bf51dc5

- name: setting repo to be executable
  file:
    path: /home/dev/bin/repo
    owner: dev
    group: dev
    mode: 0755

- name: source aosp development
  template:
    src: aosp-dev.sh
    dest: /etc/profile.d/aosp-dev.sh
  become: yes

