---
- name: installing prerequisite packages
  apt:
    name:
      - bc
      - bison
      - bsdmainutils
      - curl
      - flex
      - g++-multilib
      - git
      - gnupg
      - gperf
      - imagemagick
      - libesd0-dev
      - liblz4-tool
      - libncurses5-dev
      - libsdl1.2-dev
      - libxml2
      - libxml2-utils
      - lzop
      - maven
      - pngcrush
      - schedtool
      - squashfs-tools
      - xsltproc
      - zip
      - zlib1g-dev
    state: latest
  become: yes

- name: creating ~/bin
  file:
    path: /home/dev/bin
    state: directory
    owner: dev
    group: dev

- name: download repo
  get_url:
    url: https://storage.googleapis.com/git-repo-downloads/repo
    dest: /home/dev/bin/repo

- name: setting repo to be executable
  file:
    path: /home/dev/bin/repo
    owner: dev
    group: dev
    mode: 0755

- name: source aosp development
  template:
    src: aosp-dev.sh
    dest: /etc/profile.d/aosp-dev.sh
  become: yes

